In [2]:
import scipy
import sklearn
import sklearn.cluster
import pickle
from enum import Enum

from sklearn.decomposition import PCA
import numpy as np
from sklearn.preprocessing import StandardScaler

class Objects(Enum):
    banana=1
    bulldozer=2
    chair=3
    eyeglasses=4
    flashlight=5
    foot=6
    hand=7
    harp=8
    hat=9
    keyboard=10
    laptop=11
    nose=12
    parrot=13
    penguin=14
    pig=15
    skyscraper=16
    snowman=17
    spider=18
    trombone=19
    violin=20

def create_train():
    lengths=[]
    filename="train/"+Objects(1).name+ ".npy"
    obj_np=np.load(filename)
    obj_np=np.array(obj_np/255)
    lengths.append(len(obj_np))
    for i in range(1,20):
        filename="train/"+Objects(i+1).name+ ".npy"
        temp=np.load(filename)
        temp=np.array(temp/255)
        lengths.append(len(temp))
        obj_np=np.vstack((obj_np,temp))


#     print(lengths)
    return obj_np, lengths
        
X_train, lengths=create_train()
X_train= StandardScaler().fit_transform(X_train)

In [3]:
def create_test():
    filename="test/test.npy"
    obj_np=np.load(filename)
    return obj_np

#     print(lengths)
X_test=create_test()
X_test= StandardScaler().fit_transform(X_test)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [4]:
# print(X_test[0])

In [5]:
import csv
# print(X_train)
def csv_writer(test_answers):
    with open('answers.csv', 'w') as csvfile:
        mywriter = csv.writer(csvfile)
        mywriter.writerow(["ID", "CATEGORY"])
        for i in range(len(test_answers)):
            mywriter.writerow([i, Objects(test_answers[i]+1).name])
  

In [6]:
def createYtrain():
    Y_train=[]
    for i in range(20):
        for j in range(lengths[i]):
            temp=np.zeros((1,20))
            temp[0][i]+=1
            Y_train.append(temp[0])
    return np.array(Y_train)

def createY():
    Y_train=[]
    for i in range(20):
        for j in range(lengths[i]):
            Y_train.append(i)
    return np.array(Y_train)

Y_train=createYtrain()
print(Y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [7]:
from sklearn.model_selection import train_test_split 
# max_acc=0
# for i in range(1):
#     svm_trainX, svm_testX, svm_trainY, svm_testY = train_test_split(newX_train, Y_train, test_size=0.1, shuffle=True)

 

In [8]:
for i in range(1):
    trainX, testX, trainY, testY = train_test_split(X_train, Y_train, test_size=0.1, shuffle=True)


In [9]:
from keras.layers import Dense
from keras.models import Sequential
# np.random.seed(7)

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [10]:
model=Sequential()
model.add(Dense(2000, input_dim=784, activation='sigmoid'))
model.add(Dense(20, activation='softmax'))

In [11]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [12]:
model.fit(trainX, trainY, epochs=10, batch_size=100)

Epoch 1/10
90000/90000 [==============================] - 39s 436us/step - loss: 1.2325 - acc: 0.6384
Epoch 2/10
90000/90000 [==============================] - 38s 422us/step - loss: 0.8964 - acc: 0.7351
Epoch 3/10
90000/90000 [==============================] - 34s 377us/step - loss: 0.6981 - acc: 0.7947
Epoch 4/10
90000/90000 [==============================] - 34s 379us/step - loss: 0.5219 - acc: 0.8460
Epoch 5/10
90000/90000 [==============================] - 41s 459us/step - loss: 0.3542 - acc: 0.8982
Epoch 6/10
90000/90000 [==============================] - 34s 377us/step - loss: 0.2079 - acc: 0.9473
Epoch 7/10
90000/90000 [==============================] - 35s 385us/step - loss: 0.1025 - acc: 0.9827
Epoch 8/10
90000/90000 [==============================] - 33s 372us/step - loss: 0.0460 - acc: 0.9962
Epoch 9/10
90000/90000 [==============================] - 34s 381us/step - loss: 0.0202 - acc: 0.9995
Epoch 10/10
90000/90000 [==============================] - 36s 399us/step - loss: 

In [112]:
# print(len(testX[0]))
# huhu=np.matrix(testX[0].reshape((784,)))
# print(huhu)
myoutput=model.predict(testX)

In [113]:
# print((myoutput[0]))

[6.0144550e-05 6.2813458e-04 1.6114591e-06 3.9832923e-07 1.0240635e-04
 4.4092169e-05 1.9608638e-08 5.0149436e-05 1.2586495e-03 1.2022912e-03
 4.6949833e-07 9.5369323e-05 4.7128223e-04 4.9721883e-05 8.2135712e-06
 1.9707892e-04 9.9542505e-01 2.9612117e-06 3.9036179e-04 1.1458499e-05]


In [114]:
labels=np.argmax(myoutput, axis=1)
print(len(labels))

10000


In [115]:
print(labels)

[16  3 14 ...  3  6 16]


In [99]:
correct_labels=np.argmax(testY, axis=1)
print(correct_labels)

[10 10 14 ...  1 15 10]


In [14]:
model.evaluate(X_train, Y_train)

100000/100000 [==============================] - 19s 194us/step


[0.09125252511095255, 0.97974]

In [1]:
# fin_outp=model.predict(X_test)

# 

In [36]:
# print(fin_outp)
labels=np.argmax(fin_outp, axis=1)
print(len(labels))

100000


In [37]:
print(labels)

[ 0  8 13 ...  2  5 15]


In [38]:
csv_writer(labels)

In [15]:
from keras.models import load_model
import h5py
model.save('nn_2000_20.h5')